[package]
name = "syn_director"
version = "0.1.0"
edition = "2021"

[dependencies]
syn_core = { path = "../syn_core" }
syn_query = { path = "../syn_query" }
syn_memory = { path = "../syn_memory" }
serde = { version = "1.0", features = ["derive"] }

