name: syn
description: Simulate Your Narrative
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_rust_bridge: ^2.0.0
  ffi: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  ffigen: ^9.0.0
  integration_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
    - assets/fonts/
