[package]
name = "syn_sim"
version = "0.1.0"
edition = "2021"

[dependencies]
syn_core = { path = "../syn_core" }
syn_memory = { path = "../syn_memory" }
syn_storage = { path = "../syn_storage" }
serde = { version = "1.0", features = ["derive"] }
